// Room layouts. # wall, . floor, , and : floor variants, D doorway, space for nothing.
const racks = (letter, y) => Array.from({ length: 8 }, (_, i) => ({ k: "rack", x: 5 + i, y, row: letter, i, id: `rack${letter}` }));

export const MAPS = {
  exterior: {
    name: "Car park", bed: "outside", ambient: "#66728e", rain: true,
    floors: { ".": "asphalt", ":": "paint", ",": "puddle", D: "asphalt" },
    grid: [
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "              DD              ",
      "..............................",
      "..............................",
      "..:..:..:.....................",
      "..:..:..:..........,,.........",
      "..:..:..:.........,,,.........",
      "..............................",
      "..............................",
    ],
    props: [
      { k: "facade", x: 0, y: 0, hb: [0, 0, 480, 96], id: "facade" },
      { k: "door", x: 14, y: 6, style: "none", to: "lobby", spawn: [7, 8], face: "up", id: "frontdoor" },
      { k: "door", x: 15, y: 6, style: "none", to: "lobby", spawn: [8, 8], face: "up", id: "frontdoor" },
      { k: "car", x: 3, y: 9, id: "car" },
      { k: "lamp", x: 11, y: 8, id: "lamp" },
      { k: "lamp", x: 24, y: 8, id: "lamp" },
      { k: "bin", x: 18, y: 7, id: "extbin" },
    ],
  },

  lobby: {
    name: "Lobby", bed: "lobby", ambient: "#6c7592",
    floors: { ".": "lino", ",": "mat", D: "lino" },
    grid: [
      "################",
      "#######DD#######",
      "#..............#",
      "#..............#",
      "#..............#",
      "#..............#",
      "#..............#",
      "#..............#",
      "#..............#",
      "#......,,......#",
      "#######DD#######",
    ],
    props: [
      { k: "logo", x: 1, y: 1, id: "logo" },
      { k: "plaque", x: 5, y: 1, id: "plaque" },
      { k: "door", x: 7, y: 1, half: "l", to: "corridor", spawn: [3, 6], face: "up", id: "lobbydoor" },
      { k: "door", x: 8, y: 1, half: "r", to: "corridor", spawn: [3, 6], face: "up", id: "lobbydoor" },
      { k: "poster", x: 10, y: 1, v: 0, id: "safety" },
      { k: "clock", x: 12, y: 1, id: "clock" },
      { k: "plant", x: 1, y: 2, id: "plant" },
      { k: "plant", x: 14, y: 2, id: "plant" },
      { k: "gate", x: 6, y: 3, id: "gate" },
      { k: "gate", x: 9, y: 3, id: "gate" },
      { k: "chair", x: 3, y: 4, face: "down", id: "raychair" },
      { k: "desk", x: 2, y: 5, fw: 3, kind: "security", id: "secdesk" },
      { k: "box", x: 1, y: 7, id: "lostfound" },
      { k: "floppy", x: 1, y: 7, n: 0, hidden: true, ox: 6, oy: 2 },
      { k: "bench", x: 11, y: 6, id: "bench" },
      { k: "cooler", x: 14, y: 6, id: "cooler" },
      { k: "coin", x: 12, y: 8, n: 0 },
      { k: "door", x: 7, y: 10, style: "mat", to: "exterior", spawn: [14, 7], face: "down", id: "exitdoor" },
      { k: "door", x: 8, y: 10, style: "mat", to: "exterior", spawn: [15, 7], face: "down", id: "exitdoor" },
      { k: "spot", x: 4, y: 4, r: 58, c: "#4a5268" },
      { k: "spot", x: 11, y: 4, r: 58, c: "#4a5268" },
      { k: "spot", x: 7, y: 8, r: 50, c: "#3e4658" },
    ],
  },

  corridor: {
    name: "Corridor", bed: "corridor", ambient: "#626b88",
    floors: { ".": "lino", D: "lino" },
    grid: [
      "##################################",
      "#####D#######D#######D#####D######",
      "#................................#",
      "#................................#",
      "#................................D",
      "#................................#",
      "#................................#",
      "###D##############################",
    ],
    props: [
      { k: "poster", x: 2, y: 1, v: 1, id: "poster1" },
      { k: "door", x: 5, y: 1, sign: "BREAK", to: "break", spawn: [7, 9], face: "up", id: "breakdoor" },
      { k: "clock", x: 8, y: 1, id: "clock" },
      { k: "board", x: 9, y: 1, kind: "cork", id: "cork" },
      { k: "door", x: 13, y: 1, sign: "NOC", reader: true, to: "noc", spawn: [7, 9], face: "up", id: "nocdoor" },
      { k: "extinguisher", x: 16, y: 1, id: "ext" },
      { k: "poster", x: 18, y: 1, v: 2, id: "poster2" },
      { k: "door", x: 21, y: 1, sign: "PLANT", reader: true, style: "metal", to: "cooling", spawn: [7, 8], face: "up", id: "plantdoor" },
      { k: "poster", x: 24, y: 1, v: 3, id: "poster3" },
      { k: "door", x: 27, y: 1, sign: "ROOF", style: "stairs", id: "roofdoor" },
      { k: "extinguisher", x: 30, y: 1, id: "ext" },
      { k: "door", x: 33, y: 4, style: "side", to: "hallB", spawn: [1, 10], face: "right", id: "halldoor" },
      { k: "door", x: 3, y: 7, style: "mat", to: "lobby", spawn: [7, 2], face: "down", id: "tolobby" },
      { k: "plant", x: 1, y: 2, id: "plant" },
      { k: "bin", x: 11, y: 2, id: "bin" },
      { k: "cooler", x: 19, y: 2, id: "cooler" },
      { k: "bench", x: 15, y: 6, id: "bench" },
      { k: "coin", x: 18, y: 5, n: 1 },
      { k: "plant", x: 32, y: 2, id: "plant" },
      ...[4, 10, 16, 22, 28].map((x, i) => ({ k: "spot", x, y: 3, r: 54, c: "#454d63", flicker: i === 2 })),
    ],
  },

  break: {
    name: "Break room", bed: "break", ambient: "#6e6170",
    floors: { ".": "wood", ",": "rug", D: "wood" },
    grid: [
      "################",
      "################",
      "#..............#",
      "#..............#",
      "#..............#",
      "#......,,,,....#",
      "#......,,,,....#",
      "#......,,,,....#",
      "#..............#",
      "#..............#",
      "#######D########",
    ],
    props: [
      { k: "poster", x: 7, y: 1, v: 3, id: "mugposter" },
      { k: "clock", x: 8, y: 1, id: "clock" },
      { k: "board", x: 9, y: 1, id: "plan" },
      { k: "window", x: 11, y: 1, id: "window" },
      { k: "lockers", x: 1, y: 2, id: "lockers" },
      { k: "fridge", x: 3, y: 2, id: "fridge" },
      { k: "counter", x: 4, y: 2, id: "counter" },
      { k: "dock", x: 8, y: 2, id: "dock" },
      { k: "vending", x: 13, y: 2, id: "vending" },
      { k: "plant", x: 14, y: 2, id: "plant" },
      { k: "couch", x: 1, y: 7, id: "couch" },
      { k: "floppy", x: 1, y: 7, n: 1, hidden: true, ox: 22, oy: 0 },
      { k: "table", x: 7, y: 6, id: "table" },
      { k: "bin", x: 14, y: 8, id: "bin" },
      { k: "door", x: 7, y: 10, style: "mat", to: "corridor", spawn: [5, 2], face: "down", id: "tocorr" },
      { k: "spot", x: 4, y: 5, r: 64, c: "#5a4a3c" },
      { k: "spot", x: 10, y: 6, r: 58, c: "#54463a" },
    ],
  },

  hallB: {
    name: "Hall B", bed: "hall", ambient: "#505b78",
    floors: { ".": "raised", ",": "perf", ":": "hot", D: "raised" },
    grid: [
      "########################",
      "####################D###",
      "#......................#",
      "#...::::::::::.........#",
      "#......................#",
      "#...,,,,,,,,,,.........#",
      "#...,,,,,,,,,,.........#",
      "#...::::::::::.........#",
      "#......................#",
      "#...,,,,,,,,,,.........#",
      "D...,,,,,,,,,,.........#",
      "#...::::::::::.........#",
      "#......................#",
      "#...,,,,,,,,,,.........#",
      "#...,,,,,,,,,,.........#",
      "#...::::::::::.........#",
      "#......................#",
      "#...,,,,,,,,,,.........#",
      "#...,,,,,,,,,,.........#",
      "########################",
    ],
    props: [
      ...racks("A", 4), ...racks("B", 8), ...racks("C", 12), ...racks("D", 16),
      ...["A", "B", "C", "D"].map((l, i) => ({ k: "decal", x: 4, y: 4 + i * 4, letter: l })),
      { k: "pdu", x: 13, y: 12, id: "pdu" },
      { k: "door", x: 20, y: 1, style: "hidden", to: "room0", spawn: [5, 7], face: "up", id: "room0door" },
      { k: "cylinders", x: 1, y: 2, id: "cyl" },
      { k: "crates", x: 18, y: 2, id: "crates" },
      { k: "crates", x: 22, y: 2, id: "crates" },
      { k: "crates", x: 22, y: 3, id: "crates" },
      { k: "poster", x: 3, y: 1, v: 2, id: "hallposter" },
      { k: "extinguisher", x: 12, y: 1, id: "ext" },
      { k: "decal", x: 16, y: 2, len: 2 },
      { k: "floppy", x: 10, y: 18, n: 4 },
      { k: "door", x: 0, y: 10, style: "side", to: "corridor", spawn: [32, 4], face: "left", id: "tocorr" },
      { k: "trigger", x: 16, y: 7, fw: 7, fh: 9, id: "hallend" },
      ...[6, 10, 14, 18].map((y) => ({ k: "spot", x: 8, y, r: 54, c: "#18304f", ox: 8, oy: 0 })),
      { k: "spot", x: 19, y: 6, r: 60, c: "#262c3a" },
      { k: "spot", x: 19, y: 15, r: 60, c: "#262c3a" },
    ],
  },

  cooling: {
    name: "Cooling plant", bed: "cooling", ambient: "#5a6379",
    floors: { ".": "concrete", D: "concrete" },
    walls: "concrete",
    grid: [
      "################",
      "################",
      "#..............#",
      "#..............#",
      "#..............#",
      "#..............#",
      "#..............#",
      "#..............#",
      "#..............#",
      "#######D########",
    ],
    props: [
      { k: "pipes", x: 1, y: 1, len: 5 },
      { k: "valves", x: 6, y: 1, id: "valves" },
      { k: "pipes", x: 8, y: 1, len: 7 },
      { k: "chiller", x: 2, y: 3, id: "chiller" },
      { k: "chiller", x: 2, y: 6, id: "chiller" },
      { k: "tank", x: 13, y: 3, id: "tank" },
      { k: "floppy", x: 13, y: 3, n: 2, hidden: true, ox: 12, oy: -6 },
      { k: "drip", x: 10, y: 4, id: "drip" },
      { k: "cylinders", x: 13, y: 7, id: "cyl" },
      { k: "door", x: 7, y: 9, style: "mat", to: "corridor", spawn: [21, 2], face: "down", id: "tocorr" },
      { k: "spot", x: 8, y: 4, r: 70, c: "#353c4c" },
      { k: "spot", x: 5, y: 7, r: 40, c: "#283040" },
    ],
  },

  noc: {
    name: "NOC", bed: "noc", ambient: "#525c78",
    floors: { ".": "carpet", D: "carpet" },
    grid: [
      "################",
      "################",
      "#..............#",
      "#..............#",
      "#..............#",
      "#..............#",
      "#..............#",
      "#..............#",
      "#..............#",
      "#..............#",
      "#######D########",
    ],
    props: [
      { k: "window", x: 1, y: 1, id: "window" },
      { k: "lossWall", x: 5, y: 1, id: "losswall" },
      { k: "clock", x: 10, y: 1, id: "clock" },
      { k: "window", x: 12, y: 1, id: "window" },
      { k: "desk", x: 2, y: 4, id: "desk1" },
      { k: "chair", x: 3, y: 5, face: "up", id: "chair" },
      { k: "desk", x: 11, y: 4, id: "desk2" },
      { k: "chair", x: 11, y: 5, face: "up", id: "chair" },
      { k: "desk", x: 6, y: 6, kind: "terminal", id: "terminal" },
      { k: "chair", x: 7, y: 7, face: "up", id: "chair" },
      { k: "patch", x: 14, y: 2, id: "patch" },
      { k: "drawers", x: 1, y: 8, id: "drawers" },
      { k: "floppy", x: 1, y: 8, n: 3, hidden: true, ox: 4, oy: 0 },
      { k: "coin", x: 10, y: 8, n: 2 },
      { k: "plant", x: 14, y: 8, id: "plant" },
      { k: "door", x: 7, y: 10, style: "mat", to: "corridor", spawn: [13, 2], face: "down", id: "tocorr" },
      { k: "spot", x: 8, y: 6, r: 64, c: "#262c3c" },
    ],
  },

  room0: {
    name: "Room 0", bed: "room0", ambient: "#3c4252", dust: true,
    floors: { ".": "dusty", D: "dusty" },
    walls: "old",
    grid: [
      "############",
      "############",
      "#..........#",
      "#..........#",
      "#..........#",
      "#..........#",
      "#..........#",
      "#..........#",
      "#####D######",
    ],
    props: [
      { k: "cobweb", x: 1, y: 1 },
      { k: "cobweb", x: 10, y: 1, flip: true },
      { k: "calendar", x: 2, y: 1, id: "calendar" },
      { k: "poster", x: 8, y: 1, v: 0, id: "oldposter" },
      { k: "tower", x: 2, y: 2, id: "tower" },
      { k: "tower", x: 3, y: 2, id: "tower" },
      { k: "crt", x: 5, y: 2, id: "pip" },
      { k: "tower", x: 8, y: 2, id: "tower" },
      { k: "cabinet", x: 10, y: 2, id: "cabinet" },
      { k: "floppy", x: 10, y: 2, n: 5, hidden: true, ox: 5, oy: -10 },
      { k: "chair", x: 6, y: 3, face: "up", id: "pipchair" },
      { k: "laptop", x: 9, y: 5, id: "laptop" },
      { k: "plant", x: 1, y: 6, v: 1, id: "plant0" },
      { k: "door", x: 5, y: 8, style: "mat", to: "hallB", spawn: [20, 2], face: "down", id: "tohall" },
      { k: "trigger", x: 2, y: 3, fw: 8, fh: 3, id: "pipwake" },
    ],
  },

  roof: {
    name: "Roof", bed: "roof", ambient: "#3a4258", lamp: false,
    floors: { ".": "gravel" },
    grid: [
      "                      ",
      "                      ",
      "                      ",
      "                      ",
      "                      ",
      "                      ",
      "......................",
      "......................",
      "......................",
      "......................",
      "......................",
      "######################",
    ],
    props: [
      { k: "sky", x: 0, y: 0, hb: [0, 0, 352, 96] },
      { k: "hvac", x: 2, y: 8 },
      { k: "hvac", x: 17, y: 9 },
      { k: "mast", x: 20, y: 7 },
    ],
  },
};
